<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class AgendaEksternalKadisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('agenda_kadis_eksternal')->insert([
            [
                'tanggal_surat' => '2024-01-01',
                'no_surat' => '500.00/1',
                'pengundang' => 'Setda Prov. Jateng',
                'acara' => 'Rapat Pengendalian Inflasi Daerah secara Daring yang Dipimpin Oleh Mentri Dalam Negeri RI',
                'tanggal' => '2024-01-03', // Diubah dari "Rabu / 03 Januari 2024"
                'waktu' => '07:30',
                'tempat' => 'Ruang Rapat Gedung A Lantai II',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'nama_pendamping' => '-',
                'catatan' => '-',
                'id_bidang' => 1,
                'id_jabatan' => 1,
                'id_instruksi' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'softfile_surat' => '132-335-1-PB.pdf',
            ],
            [
                'tanggal_surat' => '2024-01-04',
                'no_surat' => '400.9.14/2',
                'pengundang' => 'Bappeda Prov. Jateng',
                'acara' => 'Desk Evaluasi Rencana Aksi Tahunan ( RAT ) Penanggulangan Kemiskinan Prov. Jateng',
                'tanggal' => '2024-01-09', // Diubah dari "8-9 Januari 2024" → ambil tanggal terakhir
                'waktu' => '09:00',
                'tempat' => 'Ruang Rapat Lantai VI A Bappeda Prov Jateng',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'nama_pendamping' => '-',
                'catatan' => '-',
                'id_bidang' => 1,
                'id_jabatan' => 2,
                'id_instruksi' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'softfile_surat' => '132-335-1-PB.pdf',
            ],
            [
                'tanggal_surat' => '2023-12-03',
                'no_surat' => '-', // karena tidak ada
                'pengundang' => 'Direktorat PDLUK',
                'acara' => 'Rakor Pemeriksaan Formulir UKL-UPL Kegiatan Rencana Penyebaran Eksplorasi Sumur DRJ-001 oleh PT. Pertamina',
                'tanggal' => '2024-01-05', // Diubah dari "Jumat / 05 Januari 2024"
                'waktu' => '08:30',
                'tempat' => 'Zoom Meeting',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'nama_pendamping' => '-',
                'catatan' => '-',
                'id_bidang' => 1,
                'id_jabatan' => 1,
                'id_instruksi' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'softfile_surat' => '132-335-1-PB.pdf',
            ],
            [
                'tanggal_surat' => '2024-01-05',
                'no_surat' => '005/4',
                'pengundang' => 'RSUD dr. Rehatta Jepara',
                'acara' => 'Pendampingan Persiapan Pengadaan Konstruksi Gedung Terpadu',
                'tanggal' => '2024-01-09', // dari "8-9 Januari 2024"
                'waktu' => '10:00',
                'tempat' => 'Litbang Lantai I RSUD dr. Rehatta Jepara',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'nama_pendamping' => '-',
                'catatan' => '-',
                'id_bidang' => 1,
                'id_jabatan' => 2,
                'id_instruksi' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'softfile_surat' => '132-335-1-PB.pdf',
            ],
            [
                'tanggal_surat' => '2024-01-05',
                'no_surat' => '-',
                'pengundang' => 'BKD',
                'acara' => 'Sosialisasi Kebijakan Mutasi pada Masa Penjabat Gubernur Jawa Tengah',
                'tanggal' => '2024-01-11',
                'waktu' => '08:30',
                'tempat' => 'zoom meeting',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'nama_pendamping' => '-',
                'catatan' => '-',
                'id_bidang' => 2,
                'id_jabatan' => 2,
                'id_instruksi' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'softfile_surat' => '132-335-1-PB.pdf',
            ],
            [
                'tanggal_surat' => '2024-01-08',
                'no_surat' => '005/3',
                'pengundang' => 'Dishub',
                'acara' => 'Peninjauan Lapangan dan Pemaparan Rutin Dokumen Hasil Andalalin',
                'tanggal' => '2024-01-12',
                'waktu' => '09:00',
                'tempat' => '-',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'nama_pendamping' => '-',
                'catatan' => '-',
                'id_bidang' => 3,
                'id_jabatan' => 6,
                'id_instruksi' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'softfile_surat' => '132-335-1-PB.pdf',
            ],
            [
                'tanggal_surat' => '2024-01-09',
                'no_surat' => '007/PAN-JT/1/2024 ',
                'pengundang' => 'PAN-JT',
                'acara' => 'Rapat Persiapan Perayaan Natal 2023 dan Tahun Baru 2024 ',
                'tanggal' => '2024-01-12',
                'waktu' => '09:00',
                'tempat' => '-',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'nama_pendamping' => '-',
                'catatan' => '-',
                'id_bidang' => 3,
                'id_jabatan' => 6,
                'id_instruksi' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'softfile_surat' => '132-335-1-PB.pdf',
            ],
            [
                'tanggal_surat' => '2024-01-8',
                'no_surat' => '000.7.3/18 ',
                'pengundang' => 'Bappeda Prov. Jateng',
                'acara' => 'Diskusi Perkembangan Proyek G11 di Jawa Tengah',
                'tanggal' => '2024-01-9',
                'waktu' => '13:00',
                'tempat' => '-',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'nama_pendamping' => '-',
                'catatan' => '-',
                'id_bidang' => 6,
                'id_jabatan' => 18,
                'id_instruksi' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'softfile_surat' => '132-335-1-PB.pdf',
            ],
            [
                'tanggal_surat' => '2024-01-8',
                'no_surat' => '005/2400216',
                'pengundang' => 'DLHK Prov. Jateng',
                'acara' => 'Pembuatan Draft Kesepakatan Bersama Antar Pemprov Jateng dengan PT. Indocement ',
                'tanggal' => '2024-01-11',
                'waktu' => '09:30',
                'tempat' => 'Ruang Adipura DLHK Prov. Jateng',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'nama_pendamping' => '-',
                'catatan' => '-',
                'id_bidang' => 2,
                'id_jabatan' => 2,
                'id_instruksi' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'softfile_surat' => '132-335-1-PB.pdf',
            ],
            [
                'tanggal_surat' => '2024-01-10',
                'no_surat' => '005/2400217',
                'pengundang' => 'DLHK Prov. Jateng',
                'acara' => 'Rapat Koordinasi Persiapan Kegiatan Hari Peduli Sampah Nasional 2024',
                'tanggal' => '2024-01-12',
                'waktu' => '10:00',
                'tempat' => 'Ruang Adipura DLHK Prov. Jateng',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'nama_pendamping' => '-',
                'catatan' => '-',
                'id_bidang' => 2,
                'id_jabatan' => 2,
                'id_instruksi' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'softfile_surat' => '132-335-1-PB.pdf',
            ],
        ]);
    }
}
